export * from "./formatedDataPaciente";
export * from "./formatedDataConsulta";
export * from "./formatedDataExamen";
export * from "./formatedDataPlanes";
export * from "./formatedDataDiagnostico";
export * from "./formatedDataTratamiento";
export * from "./formatedDataPago";
export * from "./funtionOdontogramTools";
export * from "./formatedDataOdontograma";
